# Generated by Django 4.2.14 on 2025-01-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laviapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryvideo',
            name='category',
            field=models.CharField(choices=[('Photo Editing', 'Photo Editing Pack'), ('Lightroom Presets', 'Lightroom Presets Pack'), ('Wedding Album', 'Wedding Album Designing Pack'), ('Wedding Invitation', 'Wedding Invitation Pack'), ('Photoshop Background', 'Photoshop Background PSD Pack'), ('Royal Fonts', 'Royal Fonts Pack')], default='Photo Editing', max_length=50),
        ),
    ]
